/**
 * Fonte única de verdade dos veículos de comunicação acompanhados.
 *
 * Tanto o seed do banco (`server/seed.ts`) quanto o scraper (`server/scraper.ts`)
 * leem este arquivo, evitando divergência entre a lista exibida na Metodologia,
 * os feeds RSS coletados e os metadados de transparência (propriedade,
 * ano de fundação, categoria, região).
 *
 * SOBRE A CLASSIFICAÇÃO (importante — ver página de Metodologia):
 * `spectrum` (posição no espectro político) é uma classificação DO VEÍCULO, não
 * de artigos individuais — mesmo modelo do Ground.news. É uma SIMPLIFICAÇÃO
 * ANALÍTICA e CONTESTÁVEL. Onde há cobertura, apoia-se em referências públicas:
 *   - Manchetômetro / LEMEP-IESP-UERJ — análise de valências de O Globo,
 *     Estadão e Folha (metodologia pública e citável).
 *   - Media Bias/Fact Check — cobertura parcial de veículos brasileiros.
 *   - Reuters Institute Digital News Report (Brasil) — confiança e audiência.
 *   - Literatura acadêmica de comunicação política brasileira.
 * Para veículos não cobertos por essas fontes, a classificação segue critérios
 * editoriais documentados na Metodologia e é revisada periodicamente.
 *
 * SOBRE A AVALIAÇÃO DE FACTUALIDADE (`factuality`):
 * É SEMPRE avaliação de terceiros — nunca classificação própria. O campo
 * `factualitySource` identifica a organização responsável (ex: "Media Bias/Fact Check").
 * Veículos sem cobertura externa têm factuality=undefined e não exibem badge.
 *
 * SOBRE FEEDS: `feeds` vazio = sem feed RSS público estável confirmado. O veículo
 * permanece catalogado na base de fontes (um ativo do produto), mas não é
 * coletado automaticamente até um feed válido ser adicionado.
 */

export type Spectrum =
  | "esquerda"
  | "centro-esquerda"
  | "centro"
  | "centro-direita"
  | "direita";

export type Factuality = "muito-alta" | "alta" | "mista";

/** Categoria do veículo na base de fontes. */
export type OutletCategory =
  | "mainstream" // grande imprensa
  | "regional" // foco regional/estadual
  | "publica" // estatal / institucional
  | "independente" // nativo digital / sem fins lucrativos
  | "checagem" // agência de fact-checking
  | "internacional"; // veículo estrangeiro cobrindo o Brasil

/** Status de acesso ao conteúdo. */
export type Paywall = "livre" | "parcial" | "assinatura";

export interface OutletConfig {
  name: string;
  slug: string;
  url: string;
  spectrum: Spectrum;
  ownership: string;
  foundedYear: number;
  description: string;
  /** Feeds RSS/Atom do veículo. Vazio = sem feed público estável confirmado. */
  feeds: string[];
  category: OutletCategory;
  /** Abrangência geográfica (ex: "Nacional", "SP", "DF", "Internacional"). */
  region: string;
  /** Idioma principal (ex: "pt-BR", "en", "es"). */
  language: string;
  paywall: Paywall;
  /**
   * Avaliação de factualidade atribuída por organização terceira.
   * NUNCA é classificação própria — sempre acompanhada de factualitySource.
   * Ausente = sem avaliação externa pública disponível para este veículo.
   */
  factuality?: Factuality;
  /** Nome da organização responsável pela avaliação (ex: "Media Bias/Fact Check"). */
  factualitySource?: string;
}

export const OUTLETS: OutletConfig[] = [
  // ─── Esquerda ──────────────────────────────────────────────────────────────
  {
    name: "Brasil de Fato",
    slug: "brasildefato",
    url: "https://www.brasildefato.com.br",
    spectrum: "esquerda",
    ownership: "Editora Brasil de Fato (ligada a movimentos sociais)",
    foundedYear: 2003,
    description: "Jornal popular ligado a movimentos sociais, foco em luta de classes e reforma agrária.",
    feeds: [
      "https://www.brasildefato.com.br/rss2.xml",
      "https://www.brasildefato.com.br/rss.xml",
    ],
    category: "independente",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
    factuality: "mista",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "Carta Capital",
    slug: "cartacapital",
    url: "https://www.cartacapital.com.br",
    spectrum: "esquerda",
    ownership: "Editora Confiança",
    foundedYear: 1994,
    description: "Revista semanal de análise política com viés progressista.",
    feeds: [
      "https://www.cartacapital.com.br/feed/",
      "https://www.cartacapital.com.br/politica/feed/",
    ],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "parcial",
    factuality: "alta",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "The Intercept Brasil",
    slug: "intercept",
    url: "https://www.intercept.com.br",
    spectrum: "esquerda",
    ownership: "First Look Media",
    foundedYear: 2016,
    description: "Jornalismo investigativo independente com foco em accountability e direitos.",
    feeds: ["https://www.intercept.com.br/feed/"],
    category: "independente",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
    factuality: "alta",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "Brasil 247",
    slug: "brasil247",
    url: "https://www.brasil247.com",
    spectrum: "esquerda",
    ownership: "247 Brasil Comunicação",
    foundedYear: 2011,
    description: "Portal digital de notícias e opinião com linha declaradamente de esquerda.",
    feeds: ["https://www.brasil247.com/feed"],
    category: "independente",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "Revista Fórum",
    slug: "revistaforum",
    url: "https://revistaforum.com.br",
    spectrum: "esquerda",
    ownership: "Fórum de Mídia Independente",
    foundedYear: 2001,
    description: "Revista e portal de jornalismo progressista e direitos humanos.",
    feeds: ["https://revistaforum.com.br/feed/"],
    category: "independente",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "Diário do Centro do Mundo",
    slug: "dcm",
    url: "https://www.diariodocentrodomundo.com.br",
    spectrum: "esquerda",
    ownership: "DCM",
    foundedYear: 2013,
    description: "Portal de notícias e opinião de esquerda, forte presença em redes sociais.",
    feeds: ["https://www.diariodocentrodomundo.com.br/feed/"],
    category: "independente",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },

  // ─── Centro-Esquerda ─────────────────────────────────────────────────────────
  {
    name: "Folha de S.Paulo",
    slug: "folha",
    url: "https://www.folha.uol.com.br",
    spectrum: "centro-esquerda",
    ownership: "Grupo Folha",
    foundedYear: 1921,
    description: "Um dos maiores jornais do Brasil, linha liberal-progressista e jornalismo de apartidarismo declarado.",
    feeds: [
      "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml",
      "https://feeds.folha.uol.com.br/poder/rss091.xml",
      "https://feeds.folha.uol.com.br/mercado/rss091.xml",
      "https://feeds.folha.uol.com.br/mundo/rss091.xml",
    ],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "assinatura",
    factuality: "alta",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "O Globo",
    slug: "oglobo",
    url: "https://oglobo.globo.com",
    spectrum: "centro-esquerda",
    ownership: "Grupo Globo (Família Marinho)",
    foundedYear: 1925,
    description: "Jornal carioca de grande circulação nacional, linha liberal.",
    feeds: [
      "https://oglobo.globo.com/rss.xml",
      "https://oglobo.globo.com/politica/rss.xml",
      "https://oglobo.globo.com/economia/rss.xml",
    ],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "assinatura",
    factuality: "alta",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "Agência Pública",
    slug: "apublica",
    url: "https://apublica.org",
    spectrum: "centro-esquerda",
    ownership: "Associação Pública de Jornalismo (sem fins lucrativos)",
    foundedYear: 2011,
    description: "Agência de jornalismo investigativo independente, premiada internacionalmente.",
    feeds: ["https://apublica.org/feed/"],
    category: "independente",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
    factuality: "alta",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "Nexo Jornal",
    slug: "nexo",
    url: "https://www.nexojornal.com.br",
    spectrum: "centro-esquerda",
    ownership: "Nexo Jornal Ltda.",
    foundedYear: 2015,
    description: "Jornal digital de análise contextualizada, sem publicidade, focado em dados.",
    feeds: ["https://www.nexojornal.com.br/rss.xml"],
    category: "independente",
    region: "Nacional",
    language: "pt-BR",
    paywall: "assinatura",
  },
  {
    name: "El País Brasil",
    slug: "elpaisbrasil",
    url: "https://brasil.elpais.com",
    spectrum: "centro-esquerda",
    ownership: "PRISA (Espanha)",
    foundedYear: 2013,
    description: "Edição brasileira do diário espanhol El País, cobertura de política e internacional.",
    feeds: ["https://feeds.elpais.com/mrss-s/pages/ep/site/brasil.elpais.com/portada"],
    category: "internacional",
    region: "Internacional",
    language: "pt-BR",
    paywall: "parcial",
  },
  {
    name: "Congresso em Foco",
    slug: "congressoemfoco",
    url: "https://congressoemfoco.uol.com.br",
    spectrum: "centro-esquerda",
    ownership: "Congresso em Foco (parceria UOL)",
    foundedYear: 2004,
    description: "Portal especializado em cobertura do Congresso Nacional e fiscalização do poder.",
    feeds: ["https://congressoemfoco.uol.com.br/feed/"],
    category: "independente",
    region: "DF",
    language: "pt-BR",
    paywall: "livre",
  },

  // ─── Centro ──────────────────────────────────────────────────────────────────
  {
    name: "G1",
    slug: "g1",
    url: "https://g1.globo.com",
    spectrum: "centro",
    ownership: "Grupo Globo (Família Marinho)",
    foundedYear: 2006,
    description: "Portal de notícias do Grupo Globo, cobertura factual ampla e generalista.",
    feeds: [
      "https://g1.globo.com/rss/g1/",
      "https://g1.globo.com/rss/g1/politica/",
      "https://g1.globo.com/rss/g1/economia/",
      "https://g1.globo.com/rss/g1/mundo/",
    ],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
    factuality: "alta",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "UOL",
    slug: "uol",
    url: "https://www.uol.com.br",
    spectrum: "centro",
    ownership: "Grupo UOL (Grupo Folha)",
    foundedYear: 1996,
    description: "Maior portal de conteúdo do Brasil, ampla cobertura jornalística.",
    feeds: [
      "https://rss.uol.com.br/feed/noticias.xml",
      "https://rss.uol.com.br/feed/economia.xml",
    ],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "parcial",
  },
  {
    name: "BBC News Brasil",
    slug: "bbcbrasil",
    url: "https://www.bbc.com/portuguese",
    spectrum: "centro",
    ownership: "BBC (serviço público britânico)",
    foundedYear: 2005,
    description: "Serviço em português da BBC, padrão internacional de apuração e imparcialidade.",
    feeds: ["https://feeds.bbci.co.uk/portuguese/rss.xml"],
    category: "internacional",
    region: "Internacional",
    language: "pt-BR",
    paywall: "livre",
    factuality: "muito-alta",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "Metrópoles",
    slug: "metropoles",
    url: "https://www.metropoles.com",
    spectrum: "centro",
    ownership: "Grupo Ímã (Mediabras)",
    foundedYear: 2015,
    description: "Portal de Brasília com forte cobertura de bastidores políticos e factual.",
    feeds: ["https://www.metropoles.com/feed"],
    category: "mainstream",
    region: "DF",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "CNN Brasil",
    slug: "cnnbrasil",
    url: "https://www.cnnbrasil.com.br",
    spectrum: "centro",
    ownership: "Novus Mídia",
    foundedYear: 2020,
    description: "Canal de notícias 24h e portal, cobertura factual de política e economia.",
    feeds: ["https://www.cnnbrasil.com.br/feed/"],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "IstoÉ",
    slug: "istoe",
    url: "https://istoe.com.br",
    spectrum: "centro",
    ownership: "Editora Três",
    foundedYear: 1976,
    description: "Revista semanal de informação geral e política.",
    feeds: ["https://istoe.com.br/feed/"],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "parcial",
  },
  {
    name: "Correio Braziliense",
    slug: "correiobraziliense",
    url: "https://www.correiobraziliense.com.br",
    spectrum: "centro",
    ownership: "Diários Associados",
    foundedYear: 1960,
    description: "Principal jornal de Brasília, forte cobertura do poder federal.",
    feeds: [],
    category: "regional",
    region: "DF",
    language: "pt-BR",
    paywall: "assinatura",
  },
  {
    name: "GZH (Zero Hora)",
    slug: "gzh",
    url: "https://gauchazh.clicrbs.com.br",
    spectrum: "centro",
    ownership: "Grupo RBS",
    foundedYear: 1964,
    description: "Principal veículo do Rio Grande do Sul, cobertura regional e nacional.",
    feeds: [],
    category: "regional",
    region: "RS",
    language: "pt-BR",
    paywall: "assinatura",
  },
  {
    name: "Estado de Minas",
    slug: "estadodeminas",
    url: "https://www.em.com.br",
    spectrum: "centro",
    ownership: "Diários Associados",
    foundedYear: 1928,
    description: "Maior jornal de Minas Gerais, cobertura regional e política nacional.",
    feeds: [],
    category: "regional",
    region: "MG",
    language: "pt-BR",
    paywall: "parcial",
  },
  {
    name: "O Povo",
    slug: "opovo",
    url: "https://www.opovo.com.br",
    spectrum: "centro",
    ownership: "Grupo De Olho no Tempo (O Povo)",
    foundedYear: 1928,
    description: "Principal jornal do Ceará, referência no Nordeste.",
    feeds: [],
    category: "regional",
    region: "CE",
    language: "pt-BR",
    paywall: "parcial",
  },
  {
    name: "Deutsche Welle Brasil",
    slug: "dwbrasil",
    url: "https://www.dw.com/pt-br",
    spectrum: "centro",
    ownership: "Deutsche Welle (serviço público alemão)",
    foundedYear: 2003,
    description: "Serviço em português da emissora pública alemã, cobertura internacional e do Brasil.",
    feeds: ["https://rss.dw.com/rdf/rss-br-all"],
    category: "internacional",
    region: "Internacional",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "The Brazilian Report",
    slug: "brazilianreport",
    url: "https://brazilian.report",
    spectrum: "centro",
    ownership: "The Brazilian Report",
    foundedYear: 2017,
    description: "Publicação em inglês com análise de política e economia do Brasil para audiência internacional.",
    feeds: ["https://brazilian.report/feed/"],
    category: "internacional",
    region: "Internacional",
    language: "en",
    paywall: "assinatura",
  },

  // ─── Centro-Direita ──────────────────────────────────────────────────────────
  {
    name: "Estadão",
    slug: "estadao",
    url: "https://www.estadao.com.br",
    spectrum: "centro-direita",
    ownership: "Grupo Estado (Família Mesquita)",
    foundedYear: 1875,
    description: "O Estado de S. Paulo, jornal centenário com linha liberal-conservadora.",
    feeds: [
      "https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/politica/",
      "https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/economia/",
      "https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/brasil/",
      "https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/internacional/",
    ],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "assinatura",
    factuality: "alta",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "Veja",
    slug: "veja",
    url: "https://veja.abril.com.br",
    spectrum: "centro-direita",
    ownership: "Grupo Abril",
    foundedYear: 1968,
    description: "Maior revista semanal do Brasil, linha liberal-conservadora.",
    feeds: [
      "https://veja.abril.com.br/feed/",
      "https://veja.abril.com.br/politica/feed/",
    ],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "parcial",
    factuality: "alta",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "Poder360",
    slug: "poder360",
    url: "https://www.poder360.com.br",
    spectrum: "centro-direita",
    ownership: "DrClick Comunicação",
    foundedYear: 2015,
    description: "Site de jornalismo político e econômico orientado a dados e documentos oficiais.",
    feeds: ["https://www.poder360.com.br/feed/"],
    category: "independente",
    region: "DF",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "Exame",
    slug: "exame",
    url: "https://exame.com",
    spectrum: "centro-direita",
    ownership: "Grupo BTG Pactual",
    foundedYear: 1967,
    description: "Revista e portal de economia, negócios e mercado financeiro.",
    feeds: ["https://exame.com/feed/"],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "parcial",
  },
  {
    name: "InfoMoney",
    slug: "infomoney",
    url: "https://www.infomoney.com.br",
    spectrum: "centro-direita",
    ownership: "Grupo Primo",
    foundedYear: 2000,
    description: "Portal de finanças, investimentos e mercado, orientado ao investidor.",
    feeds: ["https://www.infomoney.com.br/feed/"],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "JOTA",
    slug: "jota",
    url: "https://www.jota.info",
    spectrum: "centro-direita",
    ownership: "JOTA Informação",
    foundedYear: 2014,
    description: "Veículo especializado em Justiça, Congresso e políticas públicas.",
    feeds: ["https://www.jota.info/feed"],
    category: "independente",
    region: "DF",
    language: "pt-BR",
    paywall: "parcial",
  },

  // ─── Direita ─────────────────────────────────────────────────────────────────
  {
    name: "R7",
    slug: "r7",
    url: "https://noticias.r7.com",
    spectrum: "direita",
    ownership: "Grupo Record (Igreja Universal do Reino de Deus)",
    foundedYear: 2009,
    description: "Portal de notícias da TV Record, linha conservadora.",
    feeds: [
      "https://noticias.r7.com/feed.xml",
      "https://noticias.r7.com/brasil/feed.xml",
    ],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
    factuality: "mista",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "Gazeta do Povo",
    slug: "gazetadopovo",
    url: "https://www.gazetadopovo.com.br",
    spectrum: "direita",
    ownership: "Grupo Paranaense de Comunicação (GRPCOM)",
    foundedYear: 1919,
    description: "Jornal paranaense de alcance nacional, linha conservadora e liberal na economia.",
    feeds: ["https://www.gazetadopovo.com.br/feed/rss/republica.xml"],
    category: "mainstream",
    region: "PR",
    language: "pt-BR",
    paywall: "assinatura",
    factuality: "alta",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "Jovem Pan",
    slug: "jovempan",
    url: "https://jovempan.com.br",
    spectrum: "direita",
    ownership: "Grupo Jovem Pan",
    foundedYear: 1942,
    description: "Rádio e canal de notícias com forte linha conservadora e opinativa.",
    feeds: ["https://jovempan.com.br/feed"],
    category: "mainstream",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
    factuality: "mista",
    factualitySource: "Media Bias/Fact Check",
  },
  {
    name: "O Antagonista",
    slug: "oantagonista",
    url: "https://oantagonista.com.br",
    spectrum: "direita",
    ownership: "Crusoé / O Antagonista",
    foundedYear: 2015,
    description: "Portal de política e bastidores com linha crítica e conservadora.",
    feeds: ["https://oantagonista.com.br/feed/"],
    category: "independente",
    region: "Nacional",
    language: "pt-BR",
    paywall: "parcial",
  },
  {
    name: "Revista Oeste",
    slug: "revistaoeste",
    url: "https://revistaoeste.com",
    spectrum: "direita",
    ownership: "Oeste Mídia",
    foundedYear: 2020,
    description: "Revista e portal de linha conservadora e liberal na economia.",
    feeds: ["https://revistaoeste.com/feed/"],
    category: "independente",
    region: "Nacional",
    language: "pt-BR",
    paywall: "parcial",
  },
  {
    name: "Pleno.News",
    slug: "plenonews",
    url: "https://pleno.news",
    spectrum: "direita",
    ownership: "Pleno.News",
    foundedYear: 2018,
    description: "Portal de notícias de linha conservadora, forte presença em redes.",
    feeds: ["https://pleno.news/feed/"],
    category: "independente",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },

  // ─── Agências de Checagem (fact-checking) ────────────────────────────────────
  {
    name: "Aos Fatos",
    slug: "aosfatos",
    url: "https://www.aosfatos.org",
    spectrum: "centro",
    ownership: "Aos Fatos",
    foundedYear: 2015,
    description: "Agência de checagem de fatos e monitoramento de desinformação. Signatária do IFCN.",
    feeds: [],
    category: "checagem",
    region: "Nacional",
    language: "pt-BR",
    paywall: "parcial",
  },
  {
    name: "Agência Lupa",
    slug: "lupa",
    url: "https://lupa.uol.com.br",
    spectrum: "centro",
    ownership: "Grupo UOL",
    foundedYear: 2015,
    description: "Primeira agência de fact-checking do Brasil. Signatária do IFCN.",
    feeds: [],
    category: "checagem",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "Projeto Comprova",
    slug: "comprova",
    url: "https://checamos.afp.com/comprova",
    spectrum: "centro",
    ownership: "Consórcio de veículos brasileiros",
    foundedYear: 2018,
    description: "Coalizão de redações que verifica conteúdos suspeitos sobre políticas públicas e eleições.",
    feeds: [],
    category: "checagem",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "AFP Checamos",
    slug: "afpchecamos",
    url: "https://checamos.afp.com",
    spectrum: "centro",
    ownership: "Agence France-Presse",
    foundedYear: 2018,
    description: "Serviço de checagem em português da agência France-Presse. Signatária do IFCN.",
    feeds: [],
    category: "checagem",
    region: "Internacional",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "Fato ou Fake (G1)",
    slug: "fatooufake",
    url: "https://g1.globo.com/fato-ou-fake/",
    spectrum: "centro",
    ownership: "Grupo Globo (Família Marinho)",
    foundedYear: 2018,
    description: "Serviço de checagem do Grupo Globo, foco em conteúdos virais e eleições.",
    feeds: ["https://g1.globo.com/rss/g1/fato-ou-fake/"],
    category: "checagem",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "Boatos.org",
    slug: "boatos",
    url: "https://www.boatos.org",
    spectrum: "centro",
    ownership: "Boatos.org",
    foundedYear: 2013,
    description: "Site especializado em desmentir boatos e correntes virais.",
    feeds: ["https://www.boatos.org/feed"],
    category: "checagem",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },

  // ─── Fontes Públicas / Institucionais ────────────────────────────────────────
  {
    name: "Agência Brasil",
    slug: "agenciabrasil",
    url: "https://agenciabrasil.ebc.com.br",
    spectrum: "centro",
    ownership: "EBC — Empresa Brasil de Comunicação (estatal)",
    foundedYear: 2003,
    description: "Agência pública de notícias do governo federal, conteúdo de uso livre.",
    feeds: ["https://agenciabrasil.ebc.com.br/rss/ultimasnoticias/feed.xml"],
    category: "publica",
    region: "Nacional",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "Agência Senado",
    slug: "agenciasenado",
    url: "https://www12.senado.leg.br/noticias",
    spectrum: "centro",
    ownership: "Senado Federal",
    foundedYear: 1995,
    description: "Cobertura oficial da atividade legislativa do Senado Federal.",
    feeds: ["https://www12.senado.leg.br/noticias/rss/feed.xml"],
    category: "publica",
    region: "DF",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "Agência Câmara",
    slug: "agenciacamara",
    url: "https://www.camara.leg.br/noticias",
    spectrum: "centro",
    ownership: "Câmara dos Deputados",
    foundedYear: 2003,
    description: "Cobertura oficial da atividade legislativa da Câmara dos Deputados.",
    feeds: [],
    category: "publica",
    region: "DF",
    language: "pt-BR",
    paywall: "livre",
  },
  {
    name: "TSE — Tribunal Superior Eleitoral",
    slug: "tse",
    url: "https://www.tse.jus.br",
    spectrum: "centro",
    ownership: "Tribunal Superior Eleitoral",
    foundedYear: 1945,
    description: "Fonte oficial sobre eleições, candidaturas e combate à desinformação eleitoral.",
    feeds: [],
    category: "publica",
    region: "DF",
    language: "pt-BR",
    paywall: "livre",
  },
];

/** Mapa slug → feeds, consumido pelo scraper. */
export const RSS_FEEDS: Record<string, string[]> = Object.fromEntries(
  OUTLETS.map((o) => [o.slug, o.feeds]),
);

/**
 * Mapa slug → { rating, source } para avaliações de factualidade de terceiros.
 * Inclui apenas veículos com avaliação externa confirmada.
 * Consumido pelo frontend para exibir badges sem depender do campo DB.
 */
export const FACTUALITY_RATINGS: Record<
  string,
  { rating: Factuality; source: string } | undefined
> = Object.fromEntries(
  OUTLETS
    .filter((o) => o.factuality && o.factualitySource)
    .map((o) => [o.slug, { rating: o.factuality as Factuality, source: o.factualitySource as string }]),
);
